version: '3.8'

services:
  panel:
    build: .
    container_name: draco_panel_app
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_GENERATED_APP_KEY
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: draco_panel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: draco_panel
      MYSQL_USER: paneluser
      MYSQL_PASSWORD: panelpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
